# Generated by Django 3.2.5 on 2021-07-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210717_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginSuperuser',
            new_name='UserForJson',
        ),
    ]
